title: Nils Boden # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Data Analyst/Scientist with a passion for visualizing and presenting. Driven by curiosity, independent work, and communicating stories with Excel, SQL, and Python. 
  <br><br>
  <a href="https://www.linkedin.com/in/nils-boden-244620178/">View My LinkedIn Profile</a>
  <br>
  <a href="https://github.com/nb0401">View My GitHub Profile</a>
  <br><br>
  <a href="/imprint/imprint.html">Imprint</a>
  
#theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
